import Head from "next/head";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>NextJS Demo App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.navbar}>
          <ul>
            <li>Home</li>
            <li>About</li>
            <li>Contact</li>
          </ul>
        </div>
        <h1 className={styles.title}>Lorem ipsum.</h1>
        <p>Lorem ipsum dolor si Lorem ipsum dolor sit amet. </p>
        <div>
          <h2>Lorem, ipsum1. &rarr;</h2>
          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit.</p>

          <h2>Lorem, ipsum2. &rarr;</h2>
          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit.</p>

          <h2>Lorem, ipsum3. &rarr;</h2>
          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit.</p>

          <h2>Lorem, ipsum4. &rarr;</h2>
          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit.</p>
        </div>
      </main>
    </div>
  );
}
